apiVersion: v2
name: tm-forum-api
version: 0.14.19
appVersion: 0.13.2
kubeVersion: '>= 1.19-0'
home: https://github.com/DOME-Marketplace/tmforum-api
description: A Helm chart for running the FIWARE TMForum-APIs
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
  - fiware
  - tmforum
sources:
  - https://github.com/DOME-Marketplace/tmforum-api
maintainers:
  - name: wistefan
    email: stefan.wiedemann@fiware.org
  - name: droslbl
    email: d.ros@libelium.com
annotations:
  charts.openshift.io/name: tm-forum-api
dependencies:
  - name: redis
    version: 18.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
